//
//  TestInfo.swift
//  Gig.md
//
//  Created by Victoria Belinschi on 05.04.2022.
//

import Foundation

let job1 = JobModel(id: "1", name: "Driver for 1big bus", category: "Driving", description: "I need a driver for the 13th of April to drive our bus to New York and back", datePosted: "12.02.2022", requirements: ["Driving Licence", "Driving Car", "Not minor"], location: "New Jersey", period: "22.05.2022", employer: "Adam Sandler", price: "20 $")
let job2 = JobModel(id: "1", name: "Driver for 2big bus", category: "Driving", description: "I need a driver for the 13th of April to drive our bus to New York and back", datePosted: "12.02.2022", requirements: ["Driving Licence"], location: "New Jersey", period: "22.05.2022", employer: "Adam Sandler", price: "20 $")
let job3 = JobModel(id: "1", name: "Driver for 3big bus", category: "Driving", description: "I need a driver for the 13th of April to drive our bus to New York and back", datePosted: "12.02.2022", requirements: ["Driving Licence"], location: "New Jersey", period: "22.05.2022", employer: "Adam Sandler", price: "20 $")
let job4 = JobModel(id: "1", name: "Driver for 4big bus", category: "Driving", description: "I need a driver for the 13th of April to drive our bus to New York and back", datePosted: "12.02.2022", requirements: ["Driving Licence"], location: "New Jersey", period: "22.05.2022", employer: "Adam Sandler", price: "20 $")
let job5 = JobModel(id: "1", name: "Driver for 5big bus", category: "Driving", description: "I need a driver for the 13th of April to drive our bus to New York and back", datePosted: "12.02.2022", requirements: ["Driving Licence"], location: "New Jersey", period: "22.05.2022", employer: "Adam Sandler", price: "20 $")
let job6 = JobModel(id: "1", name: "Driver for 6big bus", category: "Driving", description: "I need a driver for the 13th of April to drive our bus to New York and back", datePosted: "12.02.2022", requirements: ["Driving Licence"], location: "New Jersey", period: "22.05.2022", employer: "Adam Sandler", price: "20 $")
let job7 = JobModel(id: "1", name: "Driver for 7big bus", category: "Driving", description: "I need a driver for the 13th of April to drive our bus to New York and back", datePosted: "12.02.2022", requirements: ["Driving Licence"], location: "New Jersey", period: "22.05.2022", employer: "Adam Sandler", price: "20 $")
let worker1 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student at the Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the free time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])
let worker2 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a studentff at the Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the free time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])
let worker3 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student atfefe the Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the free time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English", "sfsdfsdf"], certifications: [], education: ["USM Psihologie"])
let worker4 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student aefeft the Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the free time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])
let worker5 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student at tefefhe Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the free time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])
let worker6 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student at thefefe Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the free time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])
let worker7 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student aefefet the Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the free time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])
let worker8 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student at tefefefhe Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the free time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])
let worker9 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student at the Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the frefefeee time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])
let worker10 = WorkerModel(id: "1", firstName: "Lady", lastName: "Gaga", email: "lady.gaga@email.com", phoneNumber: "+37379938492", description: "I am a student at the Technical University of Moldova. I will graduate from the Software Engineering course in summer 2022. In the freefefefe time I would like to work, in order to gain some experience and make some pocket money.", adress: "str. Arborilor 21", skills: ["Drive", "Bona", "English"], certifications: [], education: ["USM Psihologie"])


var jobs: [JobModel] = [job1, job2, job3, job4, job5, job6, job7]
var workers: [WorkerModel] = [worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, worker9, worker10]

let jobCategories: [String] = ["Housekeeper", "childCare", "driver", "painter", "construction worker", "Cook", "Translator"]
